import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "none"
startup_mode = "Maximized"
option_as_alt = "Both"

[window.padding]
x = 2
y = 2

[font]
size = 16

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
# family = "Hack Nerd Font Mono"

[selection]
save_to_clipboard = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

